name: Build Docker Image

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}

jobs:
  build_docker_image:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build fake python3-libnvinfer-dev
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends fakeroot
          fakeroot dpkg-deb --build pkg/python3-libnvinfer-dev .
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: ghcr.io/nkyoku/jetson_container:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
